name: Build, Test, and Deploy ASP.Net Core app to Azure Web App - contacts-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read  # Required for actions/checkout

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'  # Adjust if needed

      - name: Restore dependencies
        run: dotnet restore my-contacts-app.sln

      - name: Build API
        run: dotnet build api/api.csproj --configuration Release --no-restore

      - name: Run Unit Tests
        run: dotnet test api.tests/api.tests.csproj --configuration Release --no-build --logger "trx;LogFileName=test-results.trx" --collect:"XPlat Code Coverage"

      - name: Publish API
        run: dotnet publish api/api.csproj -c Release -o "${{ github.workspace }}/publish"

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: .net-api
          path: "${{ github.workspace }}/publish"

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write  # Required for Azure authentication
      contents: read   # Required for actions/checkout

    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: .net-api
          path: "${{ github.workspace }}/publish"

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'contacts-app'
          slot-name: 'Production'
          package: "${{ github.workspace }}/publish"
